export { default as CalendarIco } from './CalendarIco.vue'
export { default as PenIco } from './PenIco.vue'
export { default as PlusIco } from './PlusIco.vue'
export { default as TrashIco } from './TrashIco.vue'
export { default as GoToIco } from './GoToIco.vue'

export { default as ChevronRightIco } from './ChevronRightIco.vue'
export { default as ChevronLeftIco } from './ChevronLeftIco.vue'
export { default as ChevronDownIco } from './ChevronDownIco.vue'
export { default as ChevronUpIco } from './ChevronUpIco.vue'
